// <auto-generated />
namespace twitterapp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class emailpass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(emailpass));
        
        string IMigrationMetadata.Id
        {
            get { return "202106290700433_emailpass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
